AWSTemplateFormatVersion: '2010-09-09'
Description: Arduino SiteWise data integration. For deployment and architectural details, see https://github.com/arduino/aws-sitewise-integration

Parameters:
  LambdaFunctionName:
    Type: String
    Default: sitewise-importer-function
    Description: Name of the Lambda function.

  LambdaS3Bucket:
    Type: String
    Description: S3 bucket where the Lambda function ZIP file is stored.

  LambdaS3Key:
    Type: String
    Description: S3 key for the Lambda function ZIP file.

  IotApiKey:
    Type: String
    Description: Arduino API Key.

  IotApiSecret:
    Type: String
    Description: Arduino API Secret.

  IotOrgId:
    Type: String
    Description: Arduino Organization ID (optional).

  TagFilter:
    Type: String
    Description: Filter things to import by tag (optional). Format> tag1=value1,tag2=value2

  Resolution:
    Type: Number
    Default: 300
    Description: Samples resolution in seconds. Default is 5 minutes (300s).

Resources:

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: arn:aws:ssm:*:*:parameter/sitewise-importer/*
              - Effect: Allow
                Action:
                  - iotsitewise:BatchPutAssetPropertyValue
                  - iotsitewise:DescribeAsset
                  - iotsitewise:GetAssetPropertyValue
                  - iotsitewise:ListAssetModels
                  - iotsitewise:ListAssets
                Resource: '*'

  # Lambda Function
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: bootstrap
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Runtime: provided.al2
      Timeout: 900
      MemorySize: 256

  # Parameters in Parameter Store
  ApiKeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sitewise-importer/iot/api-key
      Type: String
      Value: !Ref IotApiKey
      Tier: Standard

  ApiSecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sitewise-importer/iot/api-secret
      Type: SecureString
      Value: !Ref IotApiSecret
      Tier: Standard

  OrgIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sitewise-importer/iot/org-id
      Type: String
      Value: !Ref IotOrgId
      Tier: Standard

  FilterTagsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sitewise-importer/iot/filter/tags
      Type: String
      Value: !Ref TagFilter
      Tier: Standard

  ResolutionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sitewise-importer/iot/samples-resolution-seconds
      Type: String
      Value: !Ref Resolution
      Tier: Standard

  # EventBridge Rule to trigger Lambda every hour
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(10 * * * ? *)
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaTarget
      State: ENABLED

  # Permission for EventBridge to invoke Lambda
  LambdaPermissionForEventBridge:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBridgeRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the deployed Lambda function.
    Value: !GetAtt LambdaFunction.Arn

  LambdaExecutionRoleArn:
    Description: ARN of the IAM role associated with the Lambda function.
    Value: !GetAtt LambdaExecutionRole.Arn
